Examen/Models/Entreprise.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Examen.Models
{


    public class Entreprise
    {

        [Key]
        public int id { get; set; }

        [Required]
        [DisplayName("Nom")]
        public virtual string nom { get; set; }

        [Required]
        [DisplayName("Raison sociale")]
        public virtual string rzonSociale { get; set; }

        [Required]
        [DisplayName("Adresse")]
        public virtual string adresse { get; set; }  
    }
}

Examen/Controllers/EntrepriseController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Examen.Models;

namespace Examen.Controllers
{
    public class EntrepriseController : Controller
    {
        private ContextDbaz db = new ContextDbaz();

        // GET: /Entreprise/
        public ActionResult Index()
        {
            return View(db.entreprises.ToList());
        }

        // GET: /Entreprise/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Entreprise entreprise = db.entreprises.Find(id);
            if (entreprise == null)
            {
                return HttpNotFound();
            }
            return View(entreprise);
        }

        // GET: /Entreprise/Create
        public ActionResult Create()
        {
            return View();
        }

        public JsonResult GetEnterByNom(String nom)
        {
            string t = Request.QueryString["nom"];
            Entreprise ent = from e in db.entreprises where e.nom.Equals(t); 
            if (ent != null)
                return Json(new
                {
                    nom = ent.nom,
                    rzon  = ent.rzonSociale,
                    adress = ent.adresse
                }, JsonRequestBehavior.AllowGet);//12/06
            else
                return Json(new { data = "no" });
        }

        // POST: /Entreprise/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="id,nom,rzonSociale,adresse")] Entreprise entreprise)
        {
            if (ModelState.IsValid)
            {
                db.entreprises.Add(entreprise);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(entreprise);
        }

        // GET: /Entreprise/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Entreprise entreprise = db.entreprises.Find(id);
            if (entreprise == null)
            {
                return HttpNotFound();
            }
            return View(entreprise);
        }

        // POST: /Entreprise/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="id,nom,rzonSociale,adresse")] Entreprise entreprise)
        {
            if (ModelState.IsValid)
            {
                db.Entry(entreprise).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(entreprise);
        }

        // GET: /Entreprise/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Entreprise entreprise = db.entreprises.Find(id);
            if (entreprise == null)
            {
                return HttpNotFound();
            }
            return View(entreprise);
        }

        // POST: /Entreprise/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Entreprise entreprise = db.entreprises.Find(id);
            db.entreprises.Remove(entreprise);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Examen/Controllers/PrestationController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Examen.Models;

namespace Examen.Controllers
{
    public class PrestationController : Controller
    {
        private ContextDbaz db = new ContextDbaz();

        // GET: /Prestation/
        public ActionResult Index()
        {
            var inscriptions = db.prestations.Include(p => p.entreprise);
            return View(inscriptions.ToList());
        }

        // GET: /Prestation/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Prestation prestation = db.prestations.Find(id);
            if (prestation == null)
            {
                return HttpNotFound();
            }
            return View(prestation);
        }

        // GET: /Prestation/Create
        public ActionResult Create()
        {
            ViewBag.idEntreprise = new SelectList(db.entreprises.ToList(), "id", "nom");
            return View();
        }

        // POST: /Prestation/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="id,idEntreprise,description,nom,montant,date")] Prestation prestation)
        {
            ViewBag.idEntreprise = new SelectList(db.entreprises.ToList(), "id", "nom");

            var enter = (from ent in db.entreprises where ent.id == prestation.idEntreprise select ent).FirstOrDefault();
            prestation.entreprise = enter;

            try
            {
                db.prestations.Add(prestation);
                db.SaveChanges();
                return RedirectToAction("Index");
            }catch(Exception ee)
            {
                 return View("error");
            }
        }


        // GET: /Prestation/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Prestation prestation = db.prestations.Find(id);
            if (prestation == null)
            {
                return HttpNotFound();
            }
            ViewBag.idEntreprise = new SelectList(db.entreprises.ToList(), "id", "nom", prestation.idEntreprise);
            return View(prestation);
        }

        // POST: /Prestation/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="id,idEntreprise,description,nom,montant,date")] Prestation prestation)
        {
            ViewBag.idEntreprise = new SelectList(db.entreprises.ToList(), "id", "nom");
            var enter = (from ent in db.entreprises where ent.id == prestation.idEntreprise select ent).FirstOrDefault();
            prestation.entreprise = enter;
            prestation.montant = 1000;
          
            //var errors = ModelState.SelectMany(x => x.Value.Errors.Select(z => z.Exception));
            //if (ModelState.IsValid)
            //{
                try
                {
                    db.Entry(prestation).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch (Exception)
                {
                
                }
            //}
            prestation.description = "";
            ViewBag.idEntreprise = new SelectList(db.entreprises.ToList(), "id", "nom", prestation.idEntreprise);
            return View(prestation);
        }

        // GET: /Prestation/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Prestation prestation = db.prestations.Find(id);
            if (prestation == null)
            {
                return HttpNotFound();
            }
            return View(prestation);
        }

        // POST: /Prestation/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Prestation prestation = db.prestations.Find(id);
            db.prestations.Remove(prestation);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Examen/Views/Entreprise/Create.cshtml
@model Examen.Models.Entreprise

@{
    ViewBag.Title = "Create";
}
<script type="text/javascript" src="~/Scripts/jquery-1.10.2.js"></script>
<script type="text/javascript">

    $(document).ready(function () { //le page charge
        $(model => model.nom).change(function () { //Si le valeur du champ change
            //05/06
            alert("ok");
            $.ajax({
                url: "GetEnterByNom", //appel d la methode creer ds RH
                type: "get", //avec la methode get
                data: "tel=" + $("#tel").val(), //var url
                dataType: "json", //
                success: function (data) {
                    $.each(data, function (i, item) {
                        // alert(i);
                        if (i == "nom")
                            $("#nom").val(item)

                        if (i == "datenais")
                            $("#datenais").val(item)
                        if (i == "salaire")
                            $("#salaire").val(item)
                        if (i == "departement")
                            $("#iddept").val(item)
                        if (i == "id")
                            $("#idemp").val(item) //sa doit etre le meme nom que celui du formulaire associe
                    });
                }
            });   //permet d'utiliser ajax
        });


    });
</script>



<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Entreprise</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.nom, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nom)
                @Html.ValidationMessageFor(model => model.nom)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.rzonSociale, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.rzonSociale)
                @Html.ValidationMessageFor(model => model.rzonSociale)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.adresse, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.adresse)
                @Html.ValidationMessageFor(model => model.adresse)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Examen/Views/Entreprise/Delete.cshtml
@model Examen.Models.Entreprise

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Entreprise</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.rzonSociale)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.rzonSociale)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.adresse)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.adresse)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Examen/Views/Entreprise/Details.cshtml
@model Examen.Models.Entreprise

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Entreprise</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.rzonSociale)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.rzonSociale)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.adresse)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.adresse)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Examen/Views/Entreprise/Edit.cshtml
@model Examen.Models.Entreprise

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Entreprise</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.nom, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nom)
                @Html.ValidationMessageFor(model => model.nom)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.rzonSociale, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.rzonSociale)
                @Html.ValidationMessageFor(model => model.rzonSociale)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.adresse, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.adresse)
                @Html.ValidationMessageFor(model => model.adresse)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Examen/Views/Entreprise/Index.cshtml
@model IEnumerable<Examen.Models.Entreprise>

@{
    ViewBag.Title = "Index";
}

<h2>Entreprise</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<div>
    @Html.ActionLink("Creer prestation", "Create", "Prestation")
</div>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.nom)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.rzonSociale)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.adresse)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.nom)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.rzonSociale)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.adresse)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
            @Html.ActionLink("Details", "Details", new { id=item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id })
        </td>
    </tr>
}

</table>