Devoir/Models/Etudiant.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace DevoirsEtExams.Models
{
    public class Etudiant
    {
        [Key]
        public int id { get; set; }

        [Required]
        [DisplayName("Matricule")][StringLength(25)]
        [Index("indexUn", IsUnique=true)]
        public string matricule { get; set; }
        
        [DisplayName("Nom")]
        [Required]
        public string nom { get; set; }

        [Phone]
        [DisplayName("Telephone")]
        public string tel { get; set; }

        [DisplayName("Date Naissance")]
        public DateTime naissance { get; set; }
    }
}

Devoir/Controllers/EtudiantController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DevoirsEtExams.Models;

namespace Devoir.Controllers
{
    public class EtudiantController : Controller
    {
        private ContextDbaz db = new ContextDbaz();

        // GET: /Etudiant/
        public ActionResult Index()
        {
            var r = from e in db.Etudiants select e;
            return View(db.Etudiants.ToList());
        }

        public ActionResult listeEtudAll()
        {            
                var r = (from e in db.Etudiants select e).ToList();

                return PartialView(r);            
        }

        public ActionResult listeEtud(DateTime? date)
        {
            if(date.HasValue)
            {
                var r = (from e in db.Etudiants where e.naissance >= date select e).ToList();

                return View(r);
            }
            return View("Error");
        }

        public ActionResult Recherche()
        {

            return View();
        }

        [HttpPost]
        public ActionResult Recherche(string date)
        {
            try
            {
                DateTime d = DateTime.Parse(date);
                var r = (from e in db.Etudiants where d.CompareTo(e.naissance) == 1
                         || d.CompareTo(e.naissance) == 0
                         select e).ToList();
               
                ViewBag.li = r;

                return View("Result");
            }catch(Exception ex)
            {

            }


            return View("Error");
        }

        // GET: /Etudiant/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
 
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Etudiant etudiant = db.Etudiants.Find(id);
            if (etudiant == null)
            {
                return HttpNotFound();
            }
            return View(etudiant);
        }

        // GET: /Etudiant/Create
        public ActionResult Create()
        {
                return View();
        }

        // POST: /Etudiant/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="id,matricule,nom,tel,naissance")] Etudiant etudiant)
        {

            try
            {
                if (ModelState.IsValid)
                {
                    db.Etudiants.Add(etudiant);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

                return View(etudiant);
            }
            catch
            {

            }
            return View("error");

        }

        // GET: /Etudiant/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Etudiant etudiant = db.Etudiants.Find(id);
            if (etudiant == null)
            {
                return HttpNotFound();
            }
            return View(etudiant);
        }

        // POST: /Etudiant/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="id,matricule,nom,tel,naissance")] Etudiant etudiant)
        {
            if (ModelState.IsValid)
            {
                db.Entry(etudiant).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(etudiant);
        }

        // GET: /Etudiant/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Etudiant etudiant = db.Etudiants.Find(id);
            if (etudiant == null)
            {
                return HttpNotFound();
            }
            return View(etudiant);
        }

        // POST: /Etudiant/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Etudiant etudiant = db.Etudiants.Find(id);
            db.Etudiants.Remove(etudiant);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Devoir/Views/Etudiant/Create.cshtml
@model DevoirsEtExams.Models.Etudiant

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Etudiant</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.matricule, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.matricule)
                @Html.ValidationMessageFor(model => model.matricule)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nom, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nom)
                @Html.ValidationMessageFor(model => model.nom)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.tel, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.tel)
                @Html.ValidationMessageFor(model => model.tel)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.naissance, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.naissance)
                @Html.ValidationMessageFor(model => model.naissance)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Devoir/Views/Etudiant/Delete.cshtml
@model DevoirsEtExams.Models.Etudiant

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Etudiant</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.matricule)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.matricule)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.naissance)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.naissance)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Devoir/Views/Etudiant/Details.cshtml
@model DevoirsEtExams.Models.Etudiant

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Etudiant</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.matricule)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.matricule)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.naissance)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.naissance)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Devoir/Views/Etudiant/Edit.cshtml
@model DevoirsEtExams.Models.Etudiant

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Etudiant</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.matricule, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.matricule)
                @Html.ValidationMessageFor(model => model.matricule)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nom, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nom)
                @Html.ValidationMessageFor(model => model.nom)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.tel, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.tel)
                @Html.ValidationMessageFor(model => model.tel)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.naissance, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.naissance)
                @Html.ValidationMessageFor(model => model.naissance)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Devoir/Views/Etudiant/Index.cshtml
@model IEnumerable<DevoirsEtExams.Models.Etudiant>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
    <br />
    @Html.ActionLink("Nouvelle recherche", "Recherche", "Etudiant")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.matricule)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.nom)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.tel)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.naissance)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.matricule)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.nom)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.tel)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.naissance)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
            @Html.ActionLink("Details", "Details", new { id=item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id })
        </td>
    </tr>
}

</table>

Devoir/Views/Etudiant/Recherche.cshtml

@{
    ViewBag.Title = "Recherche";
}

<h2>Recherche</h2>



<p>
@using (Html.BeginForm("Recherche", "Etudiant"))
{
@Html.TextBox("date")   
    
<input type="submit" value="RECHERCHER" />
}
</p>

@* Element partiel a inclure *@

<div id="resultats">
    @{Html.RenderAction("listeEtudAll", "Etudiant");
    
      }
</div>


Devoir/Views/Etudiant/Result.cshtml
@model IEnumerable<DevoirsEtExams.Models.Etudiant>

@{
    ViewBag.Title = "Result";
    List<DevoirsEtExams.Models.Etudiant> list = ViewBag.li as List<DevoirsEtExams.Models.Etudiant>;
}

<h2>Result</h2>

<p>
    @Html.ActionLink("Create New", "Create")
    <br/>
    @Html.ActionLink("Nouvelle recherche", "Recherche", "Etudiant")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.matricule)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.nom)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.tel)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.naissance)
        </th>
        <th></th>
    </tr>

@foreach (var item in list) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.matricule)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.nom)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.tel)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.naissance)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
            @Html.ActionLink("Details", "Details", new { id=item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id })
        </td>
    </tr>
}

</table>

Devoir/Views/Etudiant/listeEtud.cshtml
@model IEnumerable<DevoirsEtExams.Models.Etudiant>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.matricule)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.nom)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.tel)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.naissance)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.matricule)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.nom)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.tel)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.naissance)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
            @Html.ActionLink("Details", "Details", new { id=item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id })
        </td>
    </tr>
}

</table>



Devoir/Views/Etudiant/listeEtudAll.cshtml
@model IEnumerable<DevoirsEtExams.Models.Etudiant>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.matricule)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.nom)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.tel)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.naissance)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.matricule)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.nom)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.tel)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.naissance)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
            @Html.ActionLink("Details", "Details", new { id=item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id })
        </td>
    </tr>
}

</table>