nawetAsp/Models/Reparation.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace nawetAsp.Models
{
    public class Reparation
    {
        [Key]
        public virtual int id { get; set; }

        [Required]
        [DisplayName("Description")]
        public virtual string description { get; set; }

        [Required]
        [DisplayName("Montant")]
        public virtual int montant { get; set; }

        [Required]
        [DisplayName("Date")]
        public virtual DateTime date { get; set; }

        //--------------
        [DisplayName("Materiel")]
        public virtual int idMateriel { get; set; }

        [ForeignKey("idMateriel")]
        [Required]
        public virtual Materiel materiel { get; set; }

        //-------------
        [DisplayName("Reparateur")]
        public virtual int idReparateur { get; set; }

        [ForeignKey("idReparateur")]
        [Required]
        public virtual Reparateur reparateur { get; set; }

    }
}

nawetAsp/Controllers/ReparationController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using nawetAsp.Models;
using Examen.Models;

namespace nawetAsp.Controllers
{
    public class ReparationController : Controller
    {
        private ContextDbaz db = new ContextDbaz();

        // GET: /Reparation/
        public ActionResult Index()
        {
            var reparation = db.reparation.Include(r => r.materiel).Include(r => r.reparateur);
            return View(reparation.ToList());
        }

        public ActionResult Recherche(string date)
        {
            if(date.Trim().Length > 0)
            {
                var reparation = db.reparation.Include(r => r.materiel).Include(r => r.reparateur);
                DateTime d = DateTime.Parse(date);
                var re = (from e in db.reparation
                          where d.CompareTo(e.date) == 0
                          select e).ToList();

                return View(re);
            }
            return RedirectToAction("Index");
        }

        // GET: /Reparation/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reparation reparation = db.reparation.Find(id);
            if (reparation == null)
            {
                return HttpNotFound();
            }
            return View(reparation);
        }

        // GET: /Reparation/Create
        public ActionResult Create()
        {
            ViewBag.idMateriel = new SelectList(db.materiel, "id", "reference");
            ViewBag.idReparateur = new SelectList(db.reparateur, "id", "code");
            return View();
        }

        // POST: /Reparation/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="id,description,montant,date,idMateriel,idReparateur")] Reparation reparation)
        {
            try
            {
                ViewBag.idMateriel = new SelectList(db.materiel, "id", "reference");
                ViewBag.idReparateur = new SelectList(db.reparateur, "id", "code");
                ////if (ModelState.IsValid)
                ////{
                Reparateur rep = db.reparateur.Find(reparation.idReparateur);
                Materiel mat = db.materiel.Find(reparation.idMateriel);
                reparation.reparateur = rep;
                reparation.materiel = mat;



                db.reparation.Add(reparation);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return View("error");
            }
            ////}

            //ViewBag.idMateriel = new SelectList(db.materiel, "id", "reference", reparation.idMateriel);
            //ViewBag.idReparateur = new SelectList(db.reparateur, "id", "code", reparation.idReparateur);
            //return View(reparation);
        }

        // GET: /Reparation/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reparation reparation = db.reparation.Find(id);
            if (reparation == null)
            {
                return HttpNotFound();
            }
            ViewBag.idMateriel = new SelectList(db.materiel, "id", "reference", reparation.idMateriel);
            ViewBag.idReparateur = new SelectList(db.reparateur, "id", "code", reparation.idReparateur);
            return View(reparation);
        }

        // POST: /Reparation/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="id,description,montant,date,idMateriel,idReparateur")] Reparation reparation)
        {
            if (ModelState.IsValid)
            {
                db.Entry(reparation).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.idMateriel = new SelectList(db.materiel, "id", "reference", reparation.idMateriel);
            ViewBag.idReparateur = new SelectList(db.reparateur, "id", "code", reparation.idReparateur);
            return View(reparation);
        }

        // GET: /Reparation/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reparation reparation = db.reparation.Find(id);
            if (reparation == null)
            {
                return HttpNotFound();
            }
            return View(reparation);
        }

        // POST: /Reparation/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Reparation reparation = db.reparation.Find(id);
            db.reparation.Remove(reparation);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

nawetAsp/Views/Reparation/Create.cshtml
@model nawetAsp.Models.Reparation

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Reparation</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.description, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.description)
                @Html.ValidationMessageFor(model => model.description)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.montant, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.montant)
                @Html.ValidationMessageFor(model => model.montant)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.date, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.date)
                @Html.ValidationMessageFor(model => model.date)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.idMateriel, "idMateriel", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idMateriel", String.Empty)
                @Html.ValidationMessageFor(model => model.idMateriel)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.idReparateur, "idReparateur", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idReparateur", String.Empty)
                @Html.ValidationMessageFor(model => model.idReparateur)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Rechercher", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

nawetAsp/Views/Reparation/Delete.cshtml
@model nawetAsp.Models.Reparation

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Reparation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.materiel.reference)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.materiel.reference)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.reparateur.code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.reparateur.code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.montant)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.montant)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.date)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

nawetAsp/Views/Reparation/Details.cshtml
@model nawetAsp.Models.Reparation

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Reparation</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.materiel.reference)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.materiel.reference)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.reparateur.code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.reparateur.code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.montant)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.montant)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.date)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

nawetAsp/Views/Reparation/Edit.cshtml
@model nawetAsp.Models.Reparation

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Reparation</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.description, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.description)
                @Html.ValidationMessageFor(model => model.description)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.montant, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.montant)
                @Html.ValidationMessageFor(model => model.montant)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.date, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.date)
                @Html.ValidationMessageFor(model => model.date)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.idMateriel, "idMateriel", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idMateriel", String.Empty)
                @Html.ValidationMessageFor(model => model.idMateriel)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.idReparateur, "idReparateur", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idReparateur", String.Empty)
                @Html.ValidationMessageFor(model => model.idReparateur)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

nawetAsp/Views/Reparation/Index.cshtml
@model IEnumerable<nawetAsp.Models.Reparation>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Enregistrer reparation", "Create")
</p>

<div>
@using (Html.BeginForm("Recherche", "Reparation"))
{
    @Html.TextBox("date")

    <input type="submit" value="RECHERCHER" />
}
</div>
<br/>

<table class="table">
    <tr>
        <th>
            @Html.DisplayName("Reference materiel")
        </th>

        <th>
            @Html.DisplayName("Marque")
        </th>

        <th>
            @Html.DisplayName("Code reparateur")
        </th>

        <th>
            @Html.DisplayName("Nom reparateur")
        </th>

        <th>
            @Html.DisplayNameFor(model => model.description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.montant)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.date)
        </th>
        @*<th></th>*@
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.materiel.reference)
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.materiel.marque)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.reparateur.code)
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.reparateur.nom)
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.montant)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.date)
        </td>
        @*<td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
            @Html.ActionLink("Details", "Details", new { id=item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id })
        </td>*@
    </tr>
}

</table>

nawetAsp/Views/Reparation/Recherche.cshtml
@model IEnumerable<nawetAsp.Models.Reparation>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Enregistrer reparation", "Create")
</p>

<div>
    @using (Html.BeginForm("Recherche", "Reparation"))
{
        @Html.TextBox("date")

        <input type="submit" value="RECHERCHER" />
}
</div>
<br />

@if (Model.Count() > 0) {
    
    <table class="table">
    <tr>
        <th>
            @Html.DisplayName("Reference materiel")
        </th>

        <th>
            @Html.DisplayName("Marque")
        </th>

        <th>
            @Html.DisplayName("Code reparateur")
        </th>

        <th>
            @Html.DisplayName("Nom reparateur")
        </th>

        <th>
            @Html.DisplayNameFor(model => model.description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.montant)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.date)
        </th>
        @*<th></th>*@
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.materiel.reference)
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.materiel.marque)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.reparateur.code)
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.reparateur.nom)
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.montant)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.date)
        </td>
        @*<td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
            @Html.ActionLink("Details", "Details", new { id=item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id })
        </td>*@
    </tr>
}

</table>

    }else {
    <p>
        Aucun element trouve
        </p>
}
    

nawetAsp/Views/Reparation/listePartial.cshtml
@model IEnumerable<nawetAsp.Models.Reparation>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Enregistrer reparation", "Create")
</p>

<div>
    @using (Html.BeginForm("Recherche", "Reparation"))
    {
        @Html.TextBox("date")

        <input type="submit" value="RECHERCHER" />
    }
</div>
<br />

<table class="table">
    <tr>
        <th>
            @Html.DisplayName("Materiel")
        </th>
        <th>
            @Html.DisplayName("Reparateur")
        </th>
        <th>
            @Html.DisplayNameFor(model => model.description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.montant)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.date)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.materiel.reference)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.reparateur.code)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.montant)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.date)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.id }) |
                @Html.ActionLink("Details", "Details", new { id = item.id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.id })
            </td>
        </tr>
    }

</table>